config/routes.rb
Rails.application.routes.draw do

  root "cookieshop#home_page"

  get "home" => "cookieshop#home_page"
  
  get "about" => "cookieshop#about_page"

  get "product" => "cookieshop#product_page"

  get "blog" => "cookieshop#blog_page"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cookieshop_controller.rb
class CookieshopController < ApplicationController

	def home_page
	end

	def about_page
	end

	def product_page
		@products = {
			"oatmeal raisin cookies" => {
				ingredients: ["oatmeal", "raisins", "happiness"],
				# stock_status: "in stock"
			},
			"hash brownies" => {
				ingredients: ["cocoa", "secret ingredient", "curly braces"]
				# stock_status: "backordered until June 22, 2015"
			},
			"lemon bars" => {
				ingredients: ["lemon zest", "custard", "sunshine"]
				# stock_status: "in stock"
			}
		}
	end

	def blog_page
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookieshop/about_page.html.erb
About Gran Gran's Cookie Shop

app/views/cookieshop/blog_page.html.erb
Gran's blog

app/views/cookieshop/home_page.html.erb
This is Gran Gran's Cookie Shop home page—welcome! 
<br>—Gran Gran

app/views/cookieshop/product_page.html.erb
This is Gran Gran's product page

<br>
<br>

<% @products.each do |product, attributes| %>

	<h3><%= product %></h3>
	<ul>
		<% attributes[:ingredients].each do |attribute| %>

		<li><%= attribute %></li>

		<% end %>
	</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gran Gran's Famous Cookie Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<center>
	<%= link_to "Cookie Shop Home", home_path %> • 
	<%= link_to "Gran Gran's Story", about_path %> • 
	<%= link_to "Gran Gran's Famous Cookies", product_path %> • 
	<%= link_to "Cookieriffic Blog", blog_path %>
	<p></p>
	<center>
</header>

<!-- Displays normal info -->
<%= yield %>

</body>
</html>